version: '3.9'
services:
    bot:
        image: youtube_grasper_bot:v1.0.0
        restart: always
        stop_signal: SIGINT
        environment:
            - BOT_TOKEN
            - SERVER_BOT_API
            - DB_USER
            - DB_PASSWORD
            - DB_HOST
            - DB_PORT
            - DB_NAME