version: '3.9'
services:
    bot:
        build: .
        image: youtube_grasper_bot:latest
        container_name: youtube_grasper_bot
        restart: always
        stop_signal: SIGINT
        environment:
            - BOT_TOKEN
            - SERVER_BOT_API
            - DB_USER
            - DB_PASSWORD
            - DB_HOST
            - DB_PORT
            - DB_NAME